name: CowCannon
version: '1.0.0'
main: first.minecraft.plugin.testCowCannon.TestCowCannon
api-version: '1.21'
commands:
  heal:
  cow:
    description: "Spawn an exploding cow"
    usage: "/cow [baby/set] [EntityType]"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow # permission tag
    permission-message: "You do not have permission to spawn an exploding cow"
  config:
  butterfly:
    description: "Toggle particle effect"
    usage: "/butterfly"
    permission: cowcannon.command.butterfly

# permissions configuration
permissions:
  cowcannon.command.cow:
    default: false
  cowcannon.cow.use:
    default: false